site_name: OpenCVE Documentation

repo_name: opencve/opencve-docs
repo_url: https://github.com/opencve/opencve-docs
edit_uri: ""

theme:
  logo: images/logo.png
  favicon: images/favicon.png
  name: 'material'
  palette:
    accent: blue

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition

nav:
  - Home: 'index.md'
  - Installation:
    - Manual: 'installation/manual.md'
    - Docker: 'installation/docker.md'
  - Commands:
    - celery worker: 'commands/celery_worker.md'
    - celery beat: 'commands/celery_beat.md'
    - create-user: 'commands/create_user.md'
    - import-data: 'commands/import_data.md'
    - init: 'commands/init.md'
    - upgrade-db: 'commands/upgrade_db.md'
    - webserver: 'commands/webserver.md'
  - Admin: 'admin.md'
  - Settings: 'settings.md'
  - FAQ: 'faq.md'
